### ISSUE TITLE
Link from readme no longer exists

### ISSUE THREAD

**Issue by SomeoneElseOSM** [SurajDixit/KerberosConfigMgrIIS#11]
https://blogs.msdn.microsoft.com/chiranth/2014/04/17/setting-up-kerberos-authentication-for-a-website-in-iis/

**Comment by SurajDixit** [comment]
Try the below link:

https://techcommunity.microsoft.com/t5/iis-support-blog/setting-up-kerberos-authentication-for-a-website-in-iis/ba-p/347882

Have updated the readme file as well

**Comment by SomeoneElseOSM** [comment]
Thanks
