### ISSUE TITLE
Button for cmdlet's not displayed

### ISSUE THREAD

**Issue by fzzylogic** [SurajDixit/KerberosConfigMgrIIS#2]
Great tool, thanks Suraj! Using on Windows Server 2016 Datacenter edition, I'm unable to see the button for generating the cmdlet and can't resize the window to see it. 

As a workaround, tabbed to it and pushed enter and it generated the scripts.

**Comment by SurajDixit** [comment]
Hi,

Trying to reproduce it on 2016 server. Would it be possible to share a screenshot of the issue?

**Comment by fzzylogic** [comment]
So this morning when i started up ConfigMgr, i could see the Generate Scripts button at the bottom. I clicked review and went through the options. Then i clicked 'Configure' and filled out the options. After that, i closed it with the 'x' at the top right. When i ran it again, the button was [missing from the bottom](https://i.imgur.com/d88uRXP.png) like the previous time. Tried restarting the server, then it [displays correctly again](https://i.imgur.com/F6nOA2O.png). Clicked 'Review' followed by 'yes' to all options and specified a hostname. When it was done, i closed it and re-opened it and the bottommost button was missing again. It's a traditional [virtual machine](https://i.imgur.com/2FPcpAK.png) running on Azure. Hope that helps.

**Comment by SurajDixit** [comment]
Thanks a lot for this information 👍  I was able to repro this in windows 10 also. I'm checking on it :)

**Comment by SurajDixit** [comment]
Hi, this has been fixed in v2.1. You can test it and let me know if you see the same issue.

**Comment by SurajDixit** [comment]
It has been idle.. Closing the issue..
