### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fzzylogic** [SurajDixit/KerberosConfigMgrIIS#3]
Hi Suraj, thanks again for a great tool.

When I run the current v2 on the same system where it was previously working, after clicking 'Review', it now brings up a window that says:

Fatal Error!
System.InvalidOperationException: Element not found!
  at KerberosConfigMgr.Kerberos.button2_Click(Object sender, EventArgs e)

The log contains only a Start: date entry

**Comment by SurajDixit** [comment]
Hi,

This error comes into picture if you don't have windows authentication module installed.

I assume, this is what you would be seeing in the text area:

Review:
----------
Selected Site : Default Web Site
Sitename : Default Web Site
Application Pool : DefaultAppPool
Anonymous authentication is enabled...(NOT RECOMMENDED)
Basic authentication is disabled...(RECOMMENDED)
Digest authentication is disabled...(RECOMMENDED)
ASP.NET Impersonation is disabled...(RECOMMENDED)
Windows authentication is disabled...(NOT RECOMMENDED)

Error:
---------
System.InvalidOperationException: Element not found!
   at KerberosConfigMgr.Kerberos.button2_Click(Object sender, EventArgs e)

For this you need to install Windows authentication module and then try to review it.

**Comment by fzzylogic** [comment]
Thanks Suraj, appreciate the feedback. The windows authentication module  (referring to the IIS module and setting 'Providers' for future readers) was already installed, but i had set the provider to just Negotiate:Kerberos, to disallow NTLM. After setting it to Negotiate (which includes NTLMs support), the ConfigMgr worked again. Thanks for your help!

**Comment by SurajDixit** [comment]
Thanks a lot for this information  👍

**Comment by SurajDixit** [comment]
Closing this issue..
