### ISSUE TITLE
URL in readme is dead link.

### ISSUE THREAD

**Issue by 6cef** [SurajDixit/KerberosConfigMgrIIS#6]
https://blogs.msdn.microsoft.com/surajdixit/2018/02/07/kerberos-configuration-manager-for-internet-information-services-server/

... points at a Microsoft page that says:
![image](https://user-images.githubusercontent.com/75850/51413011-7b781b00-1b3b-11e9-98b1-54d24d5663f0.png)

**Comment by jefmes** [comment]
Link is still dead as of 3/25/2019.

**Comment by SurajDixit** [comment]
Link is fixed.  Closing this... 

https://blogs.msdn.microsoft.com/surajdixit/2018/02/07/kerberos-configuration-manager-for-internet-information-services-server/
